### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by manyk** [abenevaut/laravel-settings#1]
This should be added to the README under the install process:
`$> composer require doctrine/dbal`

Important to mention or the migration will not complete successful.

**Comment by 42antoine** [comment]
Thank you to report this issue, i will analyse it asap and make change if really needed.

**Comment by 42antoine** [comment]
I updated the project and added doctrine/dbal as composer dependency.

CI : https://travis-ci.org/abenevaut/laravel-settings/builds/213828739

Thanks you again for your report.
